# Generated by Django 4.2.5 on 2023-09-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
