# Generated by Django 4.2.5 on 2023-09-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0008_alter_class_class_code_alter_class_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
