# Generated by Django 4.2.1 on 2023-09-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0010_classassigned_classmember_peereval_remarks_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacherId',
        ),
    ]
