# Generated by Django 4.2.1 on 2023-10-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0016_classmember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmember',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='classmember',
            name='role',
            field=models.CharField(default='s', max_length=2),
        ),
    ]
