# Generated by Django 4.2.5 on 2023-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0018_team_date_created_team_date_updated_team_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='recuitment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
