# Generated by Django 4.2.5 on 2023-10-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0018_peereval_date_created_peereval_date_updated_and_more'),
        ('wildforge_api', '0019_team_recuitment_status_alter_team_name'),
    ]

    operations = [
    ]
