# Generated by Django 4.2.1 on 2023-10-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0021_remove_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='peereval',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peereval',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peereval',
            name='forms_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peereval',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
