# Generated by Django 4.2.1 on 2023-10-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0025_alter_team_max_members_alter_team_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('class_member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildforge_api.classmember')),
            ],
        ),
    ]
