version: "3.8"
services:
  mysql:
    build: ./mysql
    image: mysql
    container_name: wildforge-db
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    networks:
      - wildforge-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: wildforge-db
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8088:80"
    networks:
      - wildforge-network

  # backend:
  #   build: ./
  #   image: wildforge-api
  #   container_name: wildforge-api
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./env/backend.env
  #   networks:
  #     - wildforge-network
  #   depends_on:
  #     - mysql

networks:
  wildforge-network:
    driver: bridge